### ISSUE TITLE
Porting to Switch

### ISSUE THREAD

**Issue by Hallowizer** [GaryOderNichts/bluubomb#1]
You mentioned that they recently fixed this on the Switch; I still think a Switch version could be useful for supernagged 4.x units, and for 5.x-7.x units, since Deja Vu works up to 7.x.

**Comment by GaryOderNichts** [comment]
You won't be able to just port BluuBomb to the Switch. The only thing the Switch and Wii U have in common is the underlying vulnerability.
I don't have enough experience with the Switch and won't be able to implement anything there.
