### ISSUE TITLE
Is bluubomb not working properly in the 4.0.1j version of Wii U?

### ISSUE THREAD

**Issue by lilicheng517** [GaryOderNichts/bluubomb#13]
Pairing with WiiU is normal, but WiiU enters a halted state and cannot perform any operations.  The relevant logs are as follows:
**The log output by running bluubomb:**
root# sudo ./bluubomb   8C:CD:E8:43:7F:F3
connecting to host...
connected to 8C:CD:E8:43:7F:F3
sent 803
kernel bin sent 0
sent 772
rop sent 0
pivot sent 207
cleaning up...

**The log of running the output `sudo ./ bluez-4.101/dist/sbin/bluetoothd -d -n` is as follows:**
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 9 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_cod_changed() index 0
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 10 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_new_settings() hci0 new settings
bluetoothd[2537]: Adapter /org/bluez/2537/hci0 has been disabled
bluetoothd[2537]: src/adapter.c:set_mode_complete() 
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 9 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_cod_changed() index 0
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 266 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_local_name_changed() hci0 local name changed: lizy8-Z2-Air-Series-GK5CN5X-0
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 10 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_new_settings() hci0 new settings
bluetoothd[2537]: plugins/mgmtops.c:mgmt_disable_cod_cache() index 0
bluetoothd[2537]: Adapter /org/bluez/2537/hci0 has been enabled
bluetoothd[2537]: plugins/mgmtops.c:update_settings() new settings 293
bluetoothd[2537]: src/adapter.c:adapter_mode_changed() old 0x00 new 0x02
bluetoothd[2537]: src/adapter.c:set_mode_complete() 
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 266 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_local_name_changed() hci0 local name changed: Nintendo RVL-CNT-01
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 10 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_new_settings() hci0 new settings
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 9 bytes from management socket
bluetoothd[2537]: hci0: Set Secure Simple Pairing (0x000b) failed: Busy (0x0a)
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 9 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_cod_changed() index 0
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 24 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_device_connected() hci0 device 8C:CD:E8:43:7F:F3 connected eir_len 5
bluetoothd[2537]: src/adapter.c:adapter_get_device() 8C:CD:E8:43:7F:F3
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 9 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_cod_changed() index 0
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 10 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_new_settings() hci0 new settings
bluetoothd[2537]: src/adapter.c:adapter_remove_connection() 
bluetoothd[2537]: Adapter /org/bluez/2537/hci0 has been disabled
bluetoothd[2537]: src/adapter.c:set_mode_complete() 
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 9 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_cod_changed() index 0
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 266 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_local_name_changed() hci0 local name changed: Nintendo RVL-CNT-01
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 10 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_new_settings() hci0 new settings
bluetoothd[2537]: plugins/mgmtops.c:mgmt_disable_cod_cache() index 0
bluetoothd[2537]: Adapter /org/bluez/2537/hci0 has been enabled
bluetoothd[2537]: plugins/mgmtops.c:update_settings() new settings 293
bluetoothd[2537]: src/adapter.c:adapter_mode_changed() old 0x00 new 0x02
bluetoothd[2537]: src/adapter.c:set_mode_complete() 
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 266 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_local_name_changed() hci0 local name changed: lizy8-Z2-Air-Series-GK5CN5X-0
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 9 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_cod_changed() index 0
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 10 bytes from management socket
bluetoothd[2537]: plugins/mgmtops.c:mgmt_new_settings() hci0 new settings
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() cond 1
bluetoothd[2537]: plugins/mgmtops.c:mgmt_event() Received 9 bytes from management socket
bluetoothd[2537]: hci0: Set Secure Simple Pairing (0x000b) failed: Busy (0x0a)

**Please help me to see if it is because the version is 4.0.1j that causes bluubomb to not work properly?**

**Comment by GaryOderNichts** [comment]
bluubomb only supports 5.5.X.
