### ISSUE TITLE
Rolling address

### ISSUE THREAD

**Issue by Invictaz** [GaryOderNichts/bluubomb#9]
Is the bdaddr of the WiiU fixed or rolling everytime I reboot the console?

**Comment by GaryOderNichts** [comment]
It's fixed. Please don't use issues for simple questions.

**Comment by Invictaz** [comment]
There is no e-mail address to contact you otherwise

**Comment by GaryOderNichts** [comment]
I'm probably most active on discord. You can send a friend request to Gary#4139.
